### ISSUE TITLE
npm install dependencies error

### ISSUE THREAD

**Issue by CrimsonCrow** [HanaDigital/NovelScraper#56]
npm install
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: NovelScraper@2.0.4
npm ERR! Found: @angular/compiler-cli@10.0.3
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"10.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler-cli@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"0.1102.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

log
```
39 verbose stack Error: unable to resolve dependency tree
39 verbose stack     at Arborist.[failPeerConflict] (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1143:25)
39 verbose stack     at Arborist.[loadPeerSet] (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1120:34)
39 verbose stack     at async Arborist.[buildDepStep] (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:11)
39 verbose stack     at async Arborist.buildIdealTree (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
39 verbose stack     at async Promise.all (index 1)
39 verbose stack     at async Arborist.reify (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
39 verbose stack     at async Install.install (/home/crow/.local/opt/node-v14.16.0/lib/node_modules/npm/lib/install.js:120:5)
40 verbose cwd /home/crow/git/novelscraper
41 verbose Linux 5.10.19_1
42 verbose argv "/home/crow/.local/opt/node-v14.16.0/bin/node" "/home/crow/.local/opt/node/bin/npm" "install"
43 verbose node v14.16.0
44 verbose npm  v7.6.2
45 error code ERESOLVE
46 error ERESOLVE unable to resolve dependency tree
47 error
48 error While resolving: ESC[1mNovelScraperESC[22m@ESC[1m2.0.4ESC[22m
48 error Found: ESC[1m@angular/compiler-cliESC[22m@ESC[1m10.0.3ESC[22mESC[2mESC[22m
48 error ESC[2mnode_modules/@angular/compiler-cliESC[22m
48 error   ESC[33mdevESC[39m ESC[1m@angular/compiler-cliESC[22m@"ESC[1m10.0.3ESC[22m" from the root project
48 error
48 error Could not resolve dependency:
48 error ESC[35mpeerESC[39m ESC[1m@angular/compiler-cliESC[22m@"ESC[1m^11.0.0 || ^11.2.0-nextESC[22m" from ESC[1m@angular-devkit/build-angularESC[22m@ESC[1m0.1102.2ESC[22mESC[2mESC[22m
48 error ESC[2mnode_modules/@angular-devkit/build-angularESC[22m
48 error   ESC[33mdevESC[39m ESC[1m@angular-devkit/build-angularESC[22m@"ESC[1m0.1102.2ESC[22m" from the root project
48 error
48 error Fix the upstream dependency conflict, or retry
48 error this command with --force, or --legacy-peer-deps
48 error to accept an incorrect (and potentially broken) dependency resolution.
48 error
48 error See /home/crow/.npm/eresolve-report.txt for a full report.
49 verbose exit 1
```

raw json explanation object
```
Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@angular/compiler-cli",
    "version": "10.0.3",
    "whileInstalling": {
      "name": "NovelScraper",
      "version": "2.0.4",
      "path": "/home/crow/git/novelscraper"
    },
    "location": "node_modules/@angular/compiler-cli",
    "dependents": [
      {
        "type": "dev",
        "name": "@angular/compiler-cli",
        "spec": "10.0.3",
        "from": {
          "location": "/home/crow/git/novelscraper"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "@angular/compiler-cli",
    "spec": "^11.0.0 || ^11.2.0-next",
    "error": "INVALID",
    "from": {
      "name": "@angular-devkit/build-angular",
      "version": "0.1102.2",
      "whileInstalling": {
        "name": "NovelScraper",
        "version": "2.0.4",
        "path": "/home/crow/git/novelscraper"
      },
      "location": "node_modules/@angular-devkit/build-angular",
      "dependents": [
        {
          "type": "dev",
          "name": "@angular-devkit/build-angular",
          "spec": "0.1102.2",
          "from": {
            "location": "/home/crow/git/novelscraper"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**Comment by CrimsonCrow** [comment]
fix using `npm install --legacy-peer-deps`

[reference](https://stackoverflow.com/questions/65567953/npm-i-resulting-in-many-eresolve-issues)
